theme: jekyll-theme-minimal
title: Layer2Labs
description: Build products on the top of Bitcoin
baseurl: ""
url: "https://layer2labs.github.io/"

logo: /assets/img/83122757/160809589-26d2f1b3-0090-4a36-a803-24e3144d44ad.png
layer2labspic: /assets/img/83122757/160809589-26d2f1b3-0090-4a36-a803-24e3144d44ad.png
show_downloads: false
github_username: layer2labs
